name: page-home-actions
run-name: ${{ github.actor }} page-home-actions-run
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v4
        with:
          ref: master

      - name: 配置环境
        run: mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan <your domain> >> ~/.ssh/known_hosts
          git config --global user.name 'yaochaohang'
          git config --global user.email 'yaochaohang219@gmail.com'

      - name: 远程部署
        run: ssh root@chaohangweb.cn && cd /usr/share/nginx/page-home/ && git pull && npm run docker:build